In [95]:
import pandas as pd

In [97]:
# Load the games data from an Excel file
games_df = pd.read_excel(r'C:\Users\Lenovo\Downloads/games.xlsx')
games_df

,game_id,competition_id,season,round,date,home_club_goals,away_club_goals,home_club_position,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,2222734,RU1,2012,19. Matchday,2012-12-07,2,3,11.0,10.0,Miodrag Bozovic,Slavoljub Muslin,Olimp-2,5700.0,Sergey Kuznetsov,NaN,NaN,FK Rostov,FK Krasnodar,02:03:00,domestic_league
1,2224572,DK1,2012,3. Matchday,2012-07-28,1,2,12.0,1.0,Jess Thorup,Lars Sondergaard,Blue Water Arena,5345.0,Michael Svendsen,NaN,NaN,Esbjerg fB,Sonderjyske Fc,01:02:00,domestic_league
2,2224628,DK1,2012,22. Matchday,2013-03-08,2,0,3.0,10.0,Colin Todd,Lars Sondergaard,Cepheus Park Randers,3481.0,Jakob Kehlet,NaN,NaN,Randers Fodbold Club,Sonderjyske Fc,02:00:00,domestic_league
3,2224655,DK1,2012,22. Matchday,2013-03-10,0,3,6.0,12.0,Peter Rensen,Auri Skarbalius,Ceres Park,7967.0,Kenn Hansen,NaN,NaN,Aarhus Gymnastik Forening,BRA NDBYERNES,00:03:00,domestic_league
4,2224729,DK1,2012,1. Matchday,2012-07-15,0,1,9.0,5.0,Auri Skarbalius,Troels Bech,Brondby Stadium,10806.0,Lars Christoffersen,NaN,NaN,Brondby IF,Odense Boldklub,00:01:00,domestic_league
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3263,3296153,NLP,2019,Round of 16,2020-01-22,7,0,NaN,NaN,Erik ten Hag,Eric Meijers,Johan Cruijff ArenA,52017.0,Richard Martens,NaN,NaN,AFC Ajax Amsterdam,NaN,07:00:00,domestic_cup
3264,2875216,DK1,2017,19. Matchday,2017-12-10,3,2,3.0,4.0,Kasper Hjulmand,Thomas Thomasberg,Right to Dream Park,2843.0,Michael Tykgaard,NaN,NaN,Football Club Nords,Hobro IK,03:02:00,domestic_league
3265,3099247,BE1,2018,11. Matchday,2018-10-20,3,1,9.0,7.0,Glen De Boeck,Marc Brys,Guldensporenstadion,6143.0,Wesley Alen,NaN,NaN,Koninklijke Voetbalclub Kortrijk,Koninklijke Sint-Truidense Voetbalvereniging,03:01:00,domestic_league
3266,2872273,GB1,2017,16. Matchday,2017-12-09,5,1,6.0,15.0,Mauricio Pochettino,Mark Hughes,Wembley Stadium,62202.0,Roger East,NaN,NaN,Tottenham Hotspur Football Club,Stoke City,05:01:00,domestic_league
3267,2517322,FAC,2014,Third Round,2015-01-04,3,1,NaN,NaN,Mark Hughes,Kevin Wilkin,bet365 Stadium,19423.0,Simon Hooper,NaN,NaN,Stoke City,NaN,03:01:00,domestic_cup

In [99]:
# Load the games data from an Excel file
game_lineups_df = pd.read_excel(r'C:\Users\Lenovo\Downloads/game_lineups.xlsx')
game_lineups_df

,game_lineups_id,game_id,type,number,player_id,player_name,team_captain,position
0,f2570d1504fc02f4b6c7608e8dcf89a3,4087925,substitutes,34,242284,Ethan Horvath,0,Goalkeeper
1,f5f0da93ea8e1d8bdd799658e7c8f7cb,4087928,starting_lineup,13,145466,Tim Ream,0,Centre-Back
2,31a4d12ec23d604779d909d26c1b5410,4087929,substitutes,26,578539,Chris Richards,0,Centre-Back
3,776dcbef98651450db76723cb7e3b4df,4087935,substitutes,26,578539,Chris Richards,0,Centre-Back
4,6a35ef7495303f29e7f85dbd54547fb1,4087936,starting_lineup,13,145466,Tim Ream,1,Centre-Back
...,...,...,...,...,...,...,...,...
214,ec3d266094f99ca0a8847de827e37105,4194152,starting_lineup,7,504215,Giovanni Reyna,0,Right Winger
215,667840cda9bdf3b0344b8e99b306cf38,4194152,starting_lineup,23,124732,John Anthony Brooks,0,Centre-Back
216,1c5d2f60ee777760f8a757aa10c42bb1,4194154,starting_lineup,13,103064,Terrence Boyd,0,Centre-Forward
217,99032084fd00ffbfee52c541a9f960ab,4204000,substitutes,14,315762,Luca de la Torre,0,Central Midfield
218,5c9eaf6ebb621d43a0d6fd6a9e607ef9,4220942,substitutes,13,145466,Tim Ream,0,Centre-Back

In [101]:
# Load the games data from an Excel file
game_events_df = pd.read_excel(r'C:\Users\Lenovo\Downloads/game_events.xlsx')
game_events_df

,game_event_id,date,game_id,minute,type,player_id,description,player_in_id,player_assist_id
0,c6a3c088ed8a38d4ce074dd73b20d3da,2012-08-19,2221641,62,Substitutions,1335,", Not reported",45668.0,NaN
1,02d605a5c2dc4f9a6721daa583fa5405,2012-08-26,2222536,54,Cards,1321,"1. Yellow card , Foul",NaN,NaN
2,b56c2e2e087cddb3cfe9e3d340975df9,2012-11-18,2222707,79,Substitutions,104203,", Tactical",25740.0,NaN
3,4a15d1fff4f476f48bb60092c61641d5,2012-11-23,2222721,72,Substitutions,104203,", Tactical",15583.0,NaN
4,daa97877f7edf2fda885b411d7197921,2013-05-17,2222782,63,Goals,104203,", Right-footed shot, 1. Goal of the Season Ass...",NaN,15077.0
...,...,...,...,...,...,...,...,...,...
1844,4acebccbc824e45d51045d8c5e164341,2023-10-31,4194147,3,Goals,355369,", Left-footed shot, 1. Tournament Goal Assist:...",NaN,284010.0
1845,159ad5633cf9d7c3a97b593efb6c3269,2023-10-31,4194147,9,Goals,355369,", Right-footed shot, 2. Tournament Goal Assist...",NaN,629588.0
1846,daa31f19aab26eec375884aef73c73b3,2023-10-31,4194147,65,Substitutions,355369,", Tactical",544148.0,NaN
1847,869a13060604e769290dafe0b1f14483,2023-11-01,4194152,70,Substitutions,504215,", Tactical",406640.0,NaN
1848,6b7ed06f13c1f67f0d7359c310f20ba0,2023-10-31,4194154,76,Substitutions,103064,", Tactical",378874.0,NaN

In [103]:
# Load the games data from an Excel file
appearances_df = pd.read_excel(r'C:\Users\Lenovo\Downloads/appearances.xlsx')
appearances_df

,appearance_id,game_id,player_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2224728_119169,2224728,119169,2012-07-13,Aron Johannsson,DK1,0,0,0,0,90
1,2224732_161244,2224732,161244,2012-07-14,Conor O'Brien,DK1,0,0,1,0,90
2,2224729_39467,2224729,39467,2012-07-15,Clarence Goodson,DK1,0,0,0,0,90
3,2232104_119169,2232104,119169,2012-07-19,Aron Johannsson,ELQ,0,0,0,0,74
4,2219794_39475,2219794,39475,2012-07-22,Sacha Kljestan,BESC,0,0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...
3563,3415291_537467,3415291,537467,2020-09-26,Joseph Efford,BE1,0,0,1,0,77
3564,3415296_367423,3415296,367423,2020-09-26,Chris Durkin,BE1,1,0,0,0,84
3565,3431983_478940,3431983,478940,2020-09-26,Reggie Cannon,PO1,0,0,0,0,90
3566,3450575_361104,3450575,361104,2020-09-26,Sergino Dest,NL1,0,0,0,0,6
3567,3412904_124732,3412904,124732,2020-09-27,John Anthony Brooks,L1,1,0,0,0,90

In [105]:
# Load the games data from an Excel fil
players_df = pd.read_excel(r'C:\Users\Lenovo\Downloads/players.xlsx')
players_df

,player_id,name,last_season,current_club_id,player_code,country_of_birth,date_of_birth,sub_position,position,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name
0,124732,John Anthony Brooks,2023,533,john-anthony-brooks,Germany,1993-01-28,Centre-Back,Defender,left,194.0,2000000.0,15000000.0,2024-06-30,ROGON
1,223047,Emerson Hyndman,2018,903,emerson-hyndman,United States,1996-04-09,Central Midfield,Midfield,right,170.0,800000.0,1800000.0,NaT,OmniSports
2,307781,Lynden Gooch,2016,289,lynden-gooch,United States,1995-12-24,Right Winger,Attack,right,173.0,1000000.0,1000000.0,2024-06-30,Unique Sports Group
3,370846,Timothy Weah,2023,506,timothy-weah,United States,2000-02-22,Right Midfield,Midfield,right,183.0,14000000.0,15000000.0,2028-06-30,BS Group - BS Law
4,484756,Djordje Mihailovic,2023,1090,djordje-mihailovic,United States,1998-11-10,Attacking Midfield,Midfield,NaN,178.0,5000000.0,6000000.0,2026-06-30,YMU Management Ltd.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,273570,Desevio Payne,2020,1283,desevio-payne,United States,1995-11-30,Right-Back,Defender,right,182.0,NaN,400000.0,NaT,NaN
148,111783,Alejandro Bedoya,2015,995,alejandro-bedoya,United States,1987-04-29,Central Midfield,Midfield,right,182.0,300000.0,2500000.0,2023-12-31,YMU Group
149,160670,Joe Gyau,2014,16,joe-gyau,United States,1992-09-16,Left Winger,Attack,both,175.0,400000.0,600000.0,2023-12-31,BR Group Management
150,3476,Brad Friedel,2014,148,brad-friedel,United States,1971-05-18,Goalkeeper,Goalkeeper,NaN,NaN,NaN,4000000.0,NaT,NaN
151,504215,Giovanni Reyna,2023,16,giovanni-reyna,England,2002-11-13,Attacking Midfield,Midfield,right,185.0,25000000.0,42000000.0,2025-06-30,Wasserman

In [107]:
# Merge the 'games_df' DataFrame with the 'game_lineups_df' DataFrame on the 'game_id' column
A_df = pd.merge(games_df, game_lineups_df, on = ['game_id'], how = 'left')

# Merge the resulting DataFrame 'A_df' with the 'game_events_df' DataFrame on the game_id' column
B_df = pd.merge(A_df, game_events_df, on = ['game_id'], how = 'left')

# Merge the resulting DataFrame 'B_df' with the 'appearances_df' DataFrame on the game_id' column
C_df = pd.merge(B_df, appearances_df, on = ['game_id'], how = 'left')

# Merge the resulting DataFrame 'C_df' with the 'players_df' DataFrame on the player_id' column
df1 = pd.merge(C_df, players_df, on = ['player_id'], how = 'left')

df1

,game_id,competition_id_x,season,round,date_x,home_club_goals,away_club_goals,home_club_position,away_club_position,home_club_manager_name,...,country_of_birth,date_of_birth,sub_position,position_y,foot,height_in_cm,market_value_in_eur,highest_market_value_in_eur,contract_expiration_date,agent_name
0,2222734,RU1,2012,19. Matchday,2012-12-07,2,3,11.0,10.0,Miodrag Bozovic,...,UdSSR,1988-11-17,Centre-Forward,Attack,right,175.0,NaN,500000.0,NaT,Prosport
1,2224572,DK1,2012,3. Matchday,2012-07-28,1,2,12.0,1.0,Jess Thorup,...,United States,1988-10-20,Defensive Midfield,Midfield,right,177.0,NaN,750000.0,NaT,NaN
2,2224628,DK1,2012,22. Matchday,2013-03-08,2,0,3.0,10.0,Colin Todd,...,United States,1986-06-25,Centre-Forward,Attack,right,178.0,NaN,2200000.0,NaT,NaN
3,2224655,DK1,2012,22. Matchday,2013-03-10,0,3,6.0,12.0,Peter Rensen,...,United States,1982-05-17,Centre-Back,Defender,right,193.0,NaN,1850000.0,NaT,NaN
4,2224729,DK1,2012,1. Matchday,2012-07-15,0,1,9.0,5.0,Auri Skarbalius,...,United States,1982-05-17,Centre-Back,Defender,right,193.0,NaN,1850000.0,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3804,2875216,DK1,2017,19. Matchday,2017-12-10,3,2,3.0,4.0,Kasper Hjulmand,...,Italy,1997-12-24,Right Winger,Attack,right,178.0,800000.0,1000000.0,2027-06-30,Avid Sports Group
3805,2875216,DK1,2017,19. Matchday,2017-12-10,3,2,3.0,4.0,Kasper Hjulmand,...,United States,1999-04-30,Left Winger,Attack,right,175.0,300000.0,700000.0,2024-06-30,NaN
3806,3099247,BE1,2018,11. Matchday,2018-10-20,3,1,9.0,7.0,Glen De Boeck,...,United States,1994-11-30,Centre-Back,Defender,right,185.0,800000.0,800000.0,2024-12-31,CAA Stellar
3807,2872273,GB1,2017,16. Matchday,2017-12-09,5,1,6.0,15.0,Mauricio Pochettino,...,United States,1985-07-11,Centre-Back,Defender,right,190.0,NaN,5000000.0,NaT,CMG Sports
3808,2517322,FAC,2014,Third Round,2015-01-04,3,1,NaN,NaN,Mark Hughes,...,United States,1985-07-11,Centre-Back,Defender,right,190.0,NaN,5000000.0,NaT,CMG Sports

In [109]:
# to drop the redundant columns
df1 = df1.drop(columns = ['competition_id_y', 'date_y', 'type_x', 'player_id_x', 'player_name_x', 'position_x', 'player_name_y'])
print(df1)

      game_id competition_id_x  season         round     date_x  \
0     2222734              RU1    2012  19. Matchday 2012-12-07
1     2224572              DK1    2012   3. Matchday 2012-07-28
2     2224628              DK1    2012  22. Matchday 2013-03-08
3     2224655              DK1    2012  22. Matchday 2013-03-10
4     2224729              DK1    2012   1. Matchday 2012-07-15
...       ...              ...     ...           ...        ...
3804  2875216              DK1    2017  19. Matchday 2017-12-10
3805  2875216              DK1    2017  19. Matchday 2017-12-10
3806  3099247              BE1    2018  11. Matchday 2018-10-20
3807  2872273              GB1    2017  16. Matchday 2017-12-09
3808  2517322              FAC    2014   Third Round 2015-01-04

      home_club_goals  away_club_goals  home_club_position  \
0                   2                3                11.0
1                   1                2                12.0
2                   2                0                 3.0
3                   0                3                 6.0
4                   0                1                 9.0
...               ...              ...                 ...
3804                3                2                 3.0
3805                3                2                 3.0
3806                3                1                 9.0
3807                5                1                 6.0
3808                3                1                 NaN

      away_club_position home_club_manager_name  ... country_of_birth  \
0                   10.0        Miodrag Bozovic  ...            UdSSR
1                    1.0            Jess Thorup  ...    United States
2                   10.0             Colin Todd  ...    United States
3                   12.0           Peter Rensen  ...    United States
4                    5.0        Auri Skarbalius  ...    United States
...                  ...                    ...  ...              ...
3804                 4.0        Kasper Hjulmand  ...            Italy
3805                 4.0        Kasper Hjulmand  ...    United States
3806                 7.0          Glen De Boeck  ...    United States
3807                15.0    Mauricio Pochettino  ...    United States
3808                 NaN            Mark Hughes  ...    United States

     date_of_birth        sub_position position_y   foot  height_in_cm  \
0       1988-11-17      Centre-Forward     Attack  right         175.0
1       1988-10-20  Defensive Midfield   Midfield  right         177.0
2       1986-06-25      Centre-Forward     Attack  right         178.0
3       1982-05-17         Centre-Back   Defender  right         193.0
4       1982-05-17         Centre-Back   Defender  right         193.0
...            ...                 ...        ...    ...           ...
3804    1997-12-24        Right Winger     Attack  right         178.0
3805    1999-04-30         Left Winger     Attack  right         175.0
3806    1994-11-30         Centre-Back   Defender  right         185.0
3807    1985-07-11         Centre-Back   Defender  right         190.0
3808    1985-07-11         Centre-Back   Defender  right         190.0

     market_value_in_eur highest_market_value_in_eur contract_expiration_date  \
0                    NaN                    500000.0                      NaT
1                    NaN                    750000.0                      NaT
2                    NaN                   2200000.0                      NaT
3                    NaN                   1850000.0                      NaT
4                    NaN                   1850000.0                      NaT
...                  ...                         ...                      ...
3804            800000.0                   1000000.0               2027-06-30
3805            300000.0                    700000.0               2024-06-30
3806            800000.0                    800000.0               2024-12-31
3807                 NaN                   5000000.0                      NaT
3808                 NaN                   5000000.0                      NaT

             agent_name
0              Prosport
1                   NaN
2                   NaN
3                   NaN
4                   NaN
...                 ...
3804  Avid Sports Group
3805                NaN
3806        CAA Stellar
3807         CMG Sports
3808         CMG Sports

[3809 rows x 52 columns]

In [111]:
# to see the null values present in each column
null_values = df1.isnull().sum()
print(null_values)

game_id                           0
competition_id_x                  0
season                            0
round                             0
date_x                            0
home_club_goals                   0
away_club_goals                   0
home_club_position              550
away_club_position              550
home_club_manager_name            6
away_club_manager_name            6
stadium                           0
attendance                      141
referee                           5
home_club_formation            3809
away_club_formation            3809
home_club_name                  128
away_club_name                   68
aggregate                         0
competition_type                  0
game_lineups_id                3809
number                         3809
team_captain                   3809
game_event_id                  2470
minute                         2470
type_y                         2470
player_id_y                    2470
description                    3008
player_in_id                   3067
player_assist_id               3664
appearance_id                     0
player_id                         0
date                              0
yellow_cards                      0
red_cards                         0
goals                             0
assists                           0
minutes_played                    0
name                              0
last_season                       0
current_club_id                   0
player_code                       0
country_of_birth                  0
date_of_birth                     0
sub_position                      0
position_y                        0
foot                             97
height_in_cm                     58
market_value_in_eur            1296
highest_market_value_in_eur       0
contract_expiration_date       1427
agent_name                     1106
dtype: int64

In [113]:
# to fill the null values of those columns containing the numeric values with the help of mean function

In [115]:
df1['home_club_position'] = df1['home_club_position'].fillna(df1['home_club_position'].mean())

In [117]:
df1['away_club_position'] = df1['away_club_position'].fillna(df1['away_club_position'].mean())

In [119]:
df1['attendance'] = df1['attendance'].fillna(df1['attendance'].mean())

In [121]:
df1['player_in_id'] = df1['player_in_id'].fillna(df1['player_in_id'].mean())

In [123]:
df1['player_assist_id'] = df1['player_assist_id'].fillna(df1['player_assist_id'].mean())

In [125]:
df1['height_in_cm'] = df1['height_in_cm'].fillna(df1['height_in_cm'].mean())

In [127]:
df1['market_value_in_eur'] = df1['market_value_in_eur'].fillna(df1['market_value_in_eur'].mean())

In [129]:
# checking the null values after treating the numeric value columns
null_values = df1.isnull().sum()
print(null_values)

game_id                           0
competition_id_x                  0
season                            0
round                             0
date_x                            0
home_club_goals                   0
away_club_goals                   0
home_club_position                0
away_club_position                0
home_club_manager_name            6
away_club_manager_name            6
stadium                           0
attendance                        0
referee                           5
home_club_formation            3809
away_club_formation            3809
home_club_name                  128
away_club_name                   68
aggregate                         0
competition_type                  0
game_lineups_id                3809
number                         3809
team_captain                   3809
game_event_id                  2470
minute                         2470
type_y                         2470
player_id_y                    2470
description                    3008
player_in_id                      0
player_assist_id                  0
appearance_id                     0
player_id                         0
date                              0
yellow_cards                      0
red_cards                         0
goals                             0
assists                           0
minutes_played                    0
name                              0
last_season                       0
current_club_id                   0
player_code                       0
country_of_birth                  0
date_of_birth                     0
sub_position                      0
position_y                        0
foot                             97
height_in_cm                      0
market_value_in_eur               0
highest_market_value_in_eur       0
contract_expiration_date       1427
agent_name                     1106
dtype: int64

In [131]:
# to treat the null values of those columns which contains the non numeric values

In [133]:
df1['referee'].value_counts()

referee
Dr. Felix Brych       80
Felix Zwayer          80
Marco Fritz           80
Daniel Siebert        69
Manuel Graofe         69
                      ..
Kristinn Jakobsson     1
Alper Ulusoy           1
Manuel Oliveira        1
Cosme Machado          1
Antti Munukka          1
Name: count, Length: 347, dtype: int64

In [135]:
df1['referee'] = df1['referee'].fillna('Dr. Felix Brych')

In [137]:
df1['home_club_name'].value_counts()

home_club_name
Borussia Dortmund                            117
FC Schalke 04                                111
Borussia Verein für Leibesübung 1900 e.V.    108
Eintracht Frankfurt Fuayball AG              101
Stoke City                                    98
                                            ...
Boavista Futebol Clube                         1
Athlitiki Enosi Konstantinoupoleos             1
Getafe Club  CF -football team dubai           1
De Graafschap Doetinchem                       1
Bologna Football Club 1909                     1
Name: count, Length: 253, dtype: int64

In [139]:
df1['home_club_name'] = df1['home_club_name'].fillna('Borussia Dortmund')

In [141]:
df1['away_club_name'].value_counts()

away_club_name
Borussia Dortmund                            121
FC Schalke 04                                113
eintracht frankfurt Football ag              107
Stoke City                                   105
Borussia Verein fur Leibesubung 1900 e.V.    104
                                            ...
Villarreal Club de Football S.A.D              1
PFK Stal Kamyanske (-2018)                     1
Elazigspor                                     1
Unione Sportiva Sassuolo Calcio                1
Desportivo Aves (- 2020)                       1
Name: count, Length: 255, dtype: int64

In [143]:
df1['away_club_name'] = df1['away_club_name'].fillna('Borussia Dortmund')

In [145]:
df1['game_event_id'].value_counts()

game_event_id
f30cc9b901f82261a4e6a04c4a6e2a18    3
cd800f90fe7faaf6b319ef71786b0bfd    3
bf601b2e49b85170bac65eda0f545d93    3
deb8635e7dd75779f50cee42bb2a8a8f    3
d45d60dbbc9cc9b943905f5e03deff0e    3
                                   ..
978e1846779b015f68bbfb661c98d84b    1
65d19ce7e602894779964ae8c8a2d25c    1
158381b08f41dcb0623eb85058edef46    1
b3b1ad56335307d04118347f7389b757    1
ab76dcda1ea48a36f4bc2b990a7dced2    1
Name: count, Length: 1126, dtype: int64

In [147]:
df1['game_event_id'] = df1['game_event_id'].fillna('f30cc9b901f82261a4e6a04c4a6e2a18')

In [149]:
df1['minute'].value_counts()

minute
90.0     87
46.0     51
77.0     44
74.0     40
82.0     39
         ..
15.0      1
101.0     1
97.0      1
2.0       1
91.0      1
Name: count, Length: 95, dtype: int64

In [151]:
df1['minute'] = df1['minute'].fillna('90.0')

In [153]:
df1['type_y'].value_counts()

type_y
Substitutions    744
Goals            401
Cards            194
Name: count, dtype: int64

In [155]:
df1['type_y'] = df1['type_y'].fillna('Substitutions')

In [157]:
df1['player_id_y'].value_counts()

player_id_y
119169.0    128
315779.0     85
31041.0      79
39378.0      71
49723.0      55
           ...
315762.0      1
190269.0      1
175996.0      1
3476.0        1
354613.0      1
Name: count, Length: 65, dtype: int64

In [159]:
df1['player_id_y'] = df1['player_id_y'].fillna('119169.0')

In [161]:
df1['description'].value_counts()

description
, Tactical                                                                           104
, Not reported                                                                        73
1. Yellow card  , Foul                                                                36
, Right-footed shot, 1. Goal of the Season                                            28
2. Yellow card  , Foul                                                                24
                                                                                    ...
8. Yellow card  , Foul                                                                 1
, Right-footed shot, 1. Goal of the Season Assist: , 1. Assist of the Season           1
, Left-footed shot, 3. Goal of the Season Assist: , Pass, 2. Assist of the Season      1
, Header, 2. Goal of the Season Assist: , Corner, 4. Assist of the Season              1
, Counter attack goal, 1. Tournament Goal                                              1
Name: count, Length: 231, dtype: int64

In [163]:
df1['description'] = df1['description'].fillna('Tactical')

In [165]:
df1['foot'].value_counts()

foot
right    3024
left      484
both      204
Name: count, dtype: int64

In [167]:
df1['foot'] = df1['foot'].fillna('right')

In [169]:
df1['contract_expiration_date'].value_counts()

contract_expiration_date
2024-06-30    529
2023-12-31    483
2025-06-30    423
2024-12-31    345
2027-06-30    269
2025-12-31    198
2028-06-30     61
2026-06-30     42
2023-11-30     24
2026-05-31      6
2026-12-31      2
Name: count, dtype: int64

In [171]:
df1['contract_expiration_date'] = df1['contract_expiration_date'].fillna('2024-06-30')

In [173]:
df1['agent_name'].value_counts()

agent_name
Wasserman               550
YMU Group               309
CAA Stellar             239
Robert Schneider        218
ROGON                   178
CMG Sports              176
Mega Sports             129
YMU Management Ltd.      98
PRO FC                   96
Unique Sports Group      92
Promoesport              78
Avid Sports Group        70
Gestifute                66
PROSPORT Management      48
Football Company Srl     47
SBM                      41
OmniSports               40
ARP Sportmarketing       40
Joes Blakborn            39
in4 sports               32
BS Group - BS Law        28
Prosport                 22
acta7                    10
Octagon                   9
TrueSports GmbH           8
FC Enterprise             8
TOP Agency                7
GROW                      5
PG 120 Sport Agency       4
BR Group Management       3
CCC                       3
athleteMNGment            2
Field Management          2
CAA Base Ltd              2
NVA SEG                   1
AKA Global GmbH           1
fair-sport GmbH           1
SK Soccer Tours           1
Name: count, dtype: int64

In [175]:
df1['agent_name'] = df1['agent_name'].fillna('Wasserman')

In [177]:
# to check the null values after the treatment of all the numeric and non numeric columns 
null_values = df1.isnull().sum()
print(null_values)

game_id                           0
competition_id_x                  0
season                            0
round                             0
date_x                            0
home_club_goals                   0
away_club_goals                   0
home_club_position                0
away_club_position                0
home_club_manager_name            6
away_club_manager_name            6
stadium                           0
attendance                        0
referee                           0
home_club_formation            3809
away_club_formation            3809
home_club_name                    0
away_club_name                    0
aggregate                         0
competition_type                  0
game_lineups_id                3809
number                         3809
team_captain                   3809
game_event_id                     0
minute                            0
type_y                            0
player_id_y                       0
description                       0
player_in_id                      0
player_assist_id                  0
appearance_id                     0
player_id                         0
date                              0
yellow_cards                      0
red_cards                         0
goals                             0
assists                           0
minutes_played                    0
name                              0
last_season                       0
current_club_id                   0
player_code                       0
country_of_birth                  0
date_of_birth                     0
sub_position                      0
position_y                        0
foot                              0
height_in_cm                      0
market_value_in_eur               0
highest_market_value_in_eur       0
contract_expiration_date          0
agent_name                        0
dtype: int64

In [179]:
df1['home_club_manager_name'].value_counts()

home_club_manager_name
Mark Hughes         74
Peter Rensen        67
Roberto Martínez    64
Paul Lambert        64
Lucien Favre        62
                    ..
Patrick Vieira       1
Yuri Semin           1
Bernard Blaquart     1
Stephane Jobard      1
Luis Freire          1
Name: count, Length: 580, dtype: int64

In [181]:
df1['home_club_manager_name'] = df1['home_club_manager_name'].fillna('Mark Hughes')

In [183]:
df1['away_club_manager_name'].value_counts()

away_club_manager_name
Mark Hughes         80
Paul Lambert        79
Lucien Favre        70
Roberto Martínez    63
Peter Rensen        62
                    ..
Ian Murray           1
Steve Lovell         1
Raul Procopio        1
Orest Lenczyk        1
Kevin Wilkin         1
Name: count, Length: 550, dtype: int64

In [185]:
df1['away_club_manager_name'] = df1['away_club_manager_name'].fillna('Mark Hughes')

In [187]:
null_values = df1.isnull().sum()
print(null_values)

game_id                           0
competition_id_x                  0
season                            0
round                             0
date_x                            0
home_club_goals                   0
away_club_goals                   0
home_club_position                0
away_club_position                0
home_club_manager_name            0
away_club_manager_name            0
stadium                           0
attendance                        0
referee                           0
home_club_formation            3809
away_club_formation            3809
home_club_name                    0
away_club_name                    0
aggregate                         0
competition_type                  0
game_lineups_id                3809
number                         3809
team_captain                   3809
game_event_id                     0
minute                            0
type_y                            0
player_id_y                       0
description                       0
player_in_id                      0
player_assist_id                  0
appearance_id                     0
player_id                         0
date                              0
yellow_cards                      0
red_cards                         0
goals                             0
assists                           0
minutes_played                    0
name                              0
last_season                       0
current_club_id                   0
player_code                       0
country_of_birth                  0
date_of_birth                     0
sub_position                      0
position_y                        0
foot                              0
height_in_cm                      0
market_value_in_eur               0
highest_market_value_in_eur       0
contract_expiration_date          0
agent_name                        0
dtype: int64

In [189]:
# after dropping the columns with complete empty cells in it
cleaned_data = df1.drop(columns = ['team_captain', 'number', 'game_lineups_id', 'home_club_formation', 'away_club_formation'])
print(cleaned_data)

      game_id competition_id_x  season         round     date_x  \
0     2222734              RU1    2012  19. Matchday 2012-12-07
1     2224572              DK1    2012   3. Matchday 2012-07-28
2     2224628              DK1    2012  22. Matchday 2013-03-08
3     2224655              DK1    2012  22. Matchday 2013-03-10
4     2224729              DK1    2012   1. Matchday 2012-07-15
...       ...              ...     ...           ...        ...
3804  2875216              DK1    2017  19. Matchday 2017-12-10
3805  2875216              DK1    2017  19. Matchday 2017-12-10
3806  3099247              BE1    2018  11. Matchday 2018-10-20
3807  2872273              GB1    2017  16. Matchday 2017-12-09
3808  2517322              FAC    2014   Third Round 2015-01-04

      home_club_goals  away_club_goals  home_club_position  \
0                   2                3           11.000000
1                   1                2           12.000000
2                   2                0            3.000000
3                   0                3            6.000000
4                   0                1            9.000000
...               ...              ...                 ...
3804                3                2            3.000000
3805                3                2            3.000000
3806                3                1            9.000000
3807                5                1            6.000000
3808                3                1            9.279534

      away_club_position home_club_manager_name  ... country_of_birth  \
0              10.000000        Miodrag Bozovic  ...            UdSSR
1               1.000000            Jess Thorup  ...    United States
2              10.000000             Colin Todd  ...    United States
3              12.000000           Peter Rensen  ...    United States
4               5.000000        Auri Skarbalius  ...    United States
...                  ...                    ...  ...              ...
3804            4.000000        Kasper Hjulmand  ...            Italy
3805            4.000000        Kasper Hjulmand  ...    United States
3806            7.000000          Glen De Boeck  ...    United States
3807           15.000000    Mauricio Pochettino  ...    United States
3808            9.579012            Mark Hughes  ...    United States

     date_of_birth        sub_position position_y   foot height_in_cm  \
0       1988-11-17      Centre-Forward     Attack  right        175.0
1       1988-10-20  Defensive Midfield   Midfield  right        177.0
2       1986-06-25      Centre-Forward     Attack  right        178.0
3       1982-05-17         Centre-Back   Defender  right        193.0
4       1982-05-17         Centre-Back   Defender  right        193.0
...            ...                 ...        ...    ...          ...
3804    1997-12-24        Right Winger     Attack  right        178.0
3805    1999-04-30         Left Winger     Attack  right        175.0
3806    1994-11-30         Centre-Back   Defender  right        185.0
3807    1985-07-11         Centre-Back   Defender  right        190.0
3808    1985-07-11         Centre-Back   Defender  right        190.0

     market_value_in_eur highest_market_value_in_eur contract_expiration_date  \
0           4.489216e+06                    500000.0               2024-06-30
1           4.489216e+06                    750000.0               2024-06-30
2           4.489216e+06                   2200000.0               2024-06-30
3           4.489216e+06                   1850000.0               2024-06-30
4           4.489216e+06                   1850000.0               2024-06-30
...                  ...                         ...                      ...
3804        8.000000e+05                   1000000.0               2027-06-30
3805        3.000000e+05                    700000.0               2024-06-30
3806        8.000000e+05                    800000.0               2024-12-31
3807        4.489216e+06                   5000000.0               2024-06-30
3808        4.489216e+06                   5000000.0               2024-06-30

             agent_name
0              Prosport
1             Wasserman
2             Wasserman
3             Wasserman
4             Wasserman
...                 ...
3804  Avid Sports Group
3805          Wasserman
3806        CAA Stellar
3807         CMG Sports
3808         CMG Sports

[3809 rows x 47 columns]

In [191]:
cleaned_data.to_csv('football_merged_file.csv', index=False)